[package]
name = "rcli-loader"
version = "0.1.0"
edition = "2021"

authors = ["Niklas Jensen <nikguin04@proton.me>"]
description = "RCLI-loader: The Rust client line interface loader crate, a utility built for versatile monitoring of the progress for running tasks"
readme = "readme.md"
repository = "https://github.com/nikguin04/rcli-loader"
license-file = "LICENSE"
keywords = ["cli", "async", "terminal"]
categories = ["asynchronous", "command-line-interface"]
# publish = ["rcli-loader"]

[lib]
path = "src/lib.rs"
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humansize = { version = "2.1.3", optional = true }
reqwest = { version = "0.12.22", optional = true }
terminal_size = "0.4.2"
tokio = { version = "1.46.1", features = ["full"], optional = true }

[features]
e_tokio = ["dep:tokio", "dep:humansize", "dep:reqwest"]


[[example]]
name = "basic_example"
required-features = ["e_tokio"]
